#ifndef _LD_CSKY_H_
#define _LD_CSKY_H_ 1
#include <csky-callgraph-bfd.h>

/*Mapfile*/
enum file_fmt
{
  html = 0,
  text = 1
};

typedef struct ld_csky_config_type
{
  char *cskymap_filename;
  FILE *cskymap_file;
  char *callgraph_filename;
  FILE *callgraph_file;
  int do_callgraph;
  enum file_fmt callgraph_fmt;
} ld_csky_config_type;

enum bfd_extra_type
{
  pad_enum,
  data_enum
};

enum bfd_extra_attr
{
  code_enum,
  rodata_enum,
  rwdata_enum,
  zidata_enum,
  debug_enum
};

/*Pad or Data generated by ld*/
typedef struct bfd_extra
{
  unsigned int bfd_id;
  enum bfd_extra_type type;
  enum bfd_extra_attr attr;
  size_t size;
  struct bfd_extra *next;
  struct bfd_extra *prev;
} bfd_extra;

typedef struct bfd_extra_list
{
  struct bfd_extra *head;
  struct bfd_extra *tail;
} bfd_extra_list;

/*Use for check if achive file has been printed*/
typedef struct archive_printed
{
  unsigned int bfd_id;
  struct archive_printed *next;
} archive_printed;

typedef struct archive_printed_list
{
  struct archive_printed *head;
  struct archive_printed *tail;
} archive_printed_list;

extern ld_csky_config_type csky_config;

typedef struct object_component_size
{
  int code_size;
  int rodata_size;
  int rwdata_size;
  int zidata_size;
  int debug_size;
  int code_pad;
  int rodata_pad;
  int rwdata_pad;
  int zidata_pad;
  int debug_pad;
  int code_gen;
  int rodata_gen;
  int rwdata_gen;
  int zidata_gen;
  int debug_gen;
} object_component_size;

extern void csky_lang_map (void);


/*Callgraph*/
typedef struct debug_frame_entry
{
  struct debug_frame_entry *next;
  char *augmentation;
  unsigned char fde_encoding;
  unsigned char *chunk_start;
  unsigned int code_factor;
  unsigned long pc_begin;
  unsigned long pc_range;
  int cfa_offset;
} debug_frame_entry;

extern void build_func_hash (void);
extern void set_func_stack_size (void);
extern void dump_callgraph (void);
extern bfd_boolean print_callgraph_symbol (struct callgraph_hash_entry *h,
    void *data);
extern asymbol **slurp_symtab (bfd * abfd, long *symcount, int check_flags);
extern int compare_symbols (const void *ap, const void *bp);
extern void call_graph_free (void);


#define DW_CIE_ID 0xffffffff
#define LOC_SYM_SEPARATOR "#cskycg#"
//#define CSKY_CALLGRAPH_DEBUG 1

#endif
