#ifndef __CSKY_REG_DEF_H__
#define __CSKY_REG_DEF_H__

#define GENARAL_REG_BANK      0x80000000

struct csky_reg_def
{
  int bank;
  int regno;
  const char *name;
  const char *abi_name;
/* supportes is a flag, generated by (1 << ARCH_FLAG).
   (1 << CSKY_ARCH_510)
   (1 << CSKY_ARCH_610)
   (1 << CSKY_ARCH_801)
   (1 << CSKY_ARCH_802)
   (1 << CSKY_ARCH_803)
   (1 << CSKY_ARCH_805)
   (1 << CSKY_ARCH_807)
   (1 << CSKY_ARCH_810)
   (1 << CSKY_ARCH_860)
   */
  int supportes;
  /* In some case, register is based on feature,
     like 'j', it has r23(fp)/r24(top)/
     r25(bsp)/r30(svbr) in 'ck802j'.  */
  char *features;
};

/* Shift.  */
#define SH(a) (1 << a)
/* Arch shift.  */
#define ASH(a) SH(CSKY_ARCH_##a)

#define REG_SUPPORT_ALL 0xffffffff

#define REG_SUPPORT_FEATURE 0

/* Not 801.  */
#define REG_SUPPORT_A   (REG_SUPPORT_ALL & ~ASH(801))

/* Not 801 and Not 802.  */
#define REG_SUPPORT_B   (REG_SUPPORT_ALL & ~(ASH(801) | ASH(802)))

/* Not 801, 802, 803, 805.*/
#define REG_SUPPORT_C   (REG_SUPPORT_ALL & ~(ASH(801)			\
		       	| ASH(802) | ASH(803) | ASH(805)))

/* Not 801, 802, 803, 805, 807, 810.  */
#define REG_SUPPORT_D   (REG_SUPPORT_C & ~(ASH(807) | ASH(810)))

/* Not 807, 810, 860.  */
#define REG_SUPPORT_E   (REG_SUPPORT_ALL & ~(ASH(807) | ASH(810) |	\
		       	ASH(860)))

static struct csky_reg_def csky_abiv1_general_regs[] = 
{
#ifdef DECLARE_REG
#undef DECLARE_REG
#endif

#define DECLARE_REG(regno, abi_name, support)		\
  {GENARAL_REG_BANK, regno, "r"#regno, abi_name, support, NULL}

  DECLARE_REG (0, "sp", REG_SUPPORT_ALL),
  DECLARE_REG (1, NULL, REG_SUPPORT_ALL),
  DECLARE_REG (2, "a0", REG_SUPPORT_ALL),
  DECLARE_REG (3, "a1", REG_SUPPORT_ALL),
  DECLARE_REG (4, "a2", REG_SUPPORT_ALL),
  DECLARE_REG (5, "a3", REG_SUPPORT_ALL),
  DECLARE_REG (6, "a4", REG_SUPPORT_ALL),
  DECLARE_REG (7, "a5", REG_SUPPORT_ALL),
  DECLARE_REG (8, "fp", REG_SUPPORT_ALL),
  DECLARE_REG (8, "l0", REG_SUPPORT_ALL),
  DECLARE_REG (9, "l1", REG_SUPPORT_ALL),
  DECLARE_REG (10, "l2", REG_SUPPORT_ALL),
  DECLARE_REG (11, "l3", REG_SUPPORT_ALL),
  DECLARE_REG (12, "l4", REG_SUPPORT_ALL),
  DECLARE_REG (13, "l5", REG_SUPPORT_ALL),
  DECLARE_REG (14, "gb", REG_SUPPORT_ALL),
  DECLARE_REG (15, "lr", REG_SUPPORT_ALL),
#undef DECLARE_REG
};

static struct csky_reg_def csky_abiv1_control_regs[] = 
{
#ifdef DECLARE_REG
#undef DECLARE_REG
#endif
#define DECLARE_REG(regno, abi_name, support)		\
  {0, regno, "cr"#regno, abi_name, support, NULL}

  DECLARE_REG (0, "psr", REG_SUPPORT_ALL),
  DECLARE_REG (1, "vbr", REG_SUPPORT_ALL),
  DECLARE_REG (2, "epsr", REG_SUPPORT_ALL),
  DECLARE_REG (3, "fpsr", REG_SUPPORT_ALL),
  DECLARE_REG (4, "epc", REG_SUPPORT_ALL),
  DECLARE_REG (5, "fpc", REG_SUPPORT_ALL),
  DECLARE_REG (6, "ss0", REG_SUPPORT_ALL),
  DECLARE_REG (7, "ss1", REG_SUPPORT_ALL),
  DECLARE_REG (8, "ss2", REG_SUPPORT_ALL),
  DECLARE_REG (9, "ss3", REG_SUPPORT_ALL),
  DECLARE_REG (10, "ss4", REG_SUPPORT_ALL),
  DECLARE_REG (11, "gcr", REG_SUPPORT_ALL),
  DECLARE_REG (12, "gsr", REG_SUPPORT_ALL),
  DECLARE_REG (13, "cpid", REG_SUPPORT_ALL),
  DECLARE_REG (14, "dcsr", REG_SUPPORT_ALL),
  DECLARE_REG (15, "cwr", REG_SUPPORT_ALL),
  DECLARE_REG (16, NULL, REG_SUPPORT_ALL),
  DECLARE_REG (17, "cfr", REG_SUPPORT_ALL),
  DECLARE_REG (18, "ccr", REG_SUPPORT_ALL),
  DECLARE_REG (19, "capr", REG_SUPPORT_ALL),
  DECLARE_REG (20, "pacr", REG_SUPPORT_ALL),
  DECLARE_REG (21, "prsr", REG_SUPPORT_ALL),
  DECLARE_REG (22, "mir", REG_SUPPORT_ALL),
  DECLARE_REG (23, "mrr", REG_SUPPORT_ALL),
  DECLARE_REG (24, "mel0", REG_SUPPORT_ALL),
  DECLARE_REG (25, "mel1", REG_SUPPORT_ALL),
  DECLARE_REG (26, "meh", REG_SUPPORT_ALL),
  DECLARE_REG (27, "mcr", REG_SUPPORT_ALL),
  DECLARE_REG (28, "mpr", REG_SUPPORT_ALL),
  DECLARE_REG (29, "mwr", REG_SUPPORT_ALL),
  DECLARE_REG (30, "mcir", REG_SUPPORT_ALL),
#undef DECLARE_REG
};

static struct csky_reg_def csky_abiv2_general_regs[] = 
{
#ifdef DECLARE_REG
#undef DECLARE_REG
#endif
#define DECLARE_REG(regno, abi_name, support)		\
  {GENARAL_REG_BANK, regno, "r"#regno, abi_name, support, NULL}

  DECLARE_REG (0, "a0", REG_SUPPORT_ALL),
  DECLARE_REG (1, "a1", REG_SUPPORT_ALL),
  DECLARE_REG (2, "a2", REG_SUPPORT_ALL),
  DECLARE_REG (3, "a3", REG_SUPPORT_ALL),
  DECLARE_REG (4, "l0", REG_SUPPORT_ALL),
  DECLARE_REG (5, "l1", REG_SUPPORT_ALL),
  DECLARE_REG (6, "l2", REG_SUPPORT_ALL),
  DECLARE_REG (7, "l3", REG_SUPPORT_ALL),
  DECLARE_REG (8, "l4", REG_SUPPORT_ALL),
  DECLARE_REG (9, "l5", REG_SUPPORT_A),
  DECLARE_REG (10, "l6", REG_SUPPORT_A),
  DECLARE_REG (11, "l7", REG_SUPPORT_A),
  DECLARE_REG (12, "t0", REG_SUPPORT_A),
  DECLARE_REG (13, "t1", REG_SUPPORT_ALL),
  DECLARE_REG (14, "sp", REG_SUPPORT_ALL),
  DECLARE_REG (15, "lr", REG_SUPPORT_ALL),
  DECLARE_REG (16, "l8", REG_SUPPORT_B),
  DECLARE_REG (17, "l9", REG_SUPPORT_B),
  DECLARE_REG (18, "t2", REG_SUPPORT_B),
  DECLARE_REG (19, "t3", REG_SUPPORT_B),
  DECLARE_REG (20, "t4", REG_SUPPORT_B),
  DECLARE_REG (21, "t5", REG_SUPPORT_B),
  DECLARE_REG (22, "t6", REG_SUPPORT_B),
  DECLARE_REG (23, "t7", REG_SUPPORT_B),
  DECLARE_REG (24, "t8", REG_SUPPORT_B),
  DECLARE_REG (25, "t9", REG_SUPPORT_B),
  DECLARE_REG (26, NULL, REG_SUPPORT_B),
  DECLARE_REG (27, NULL, REG_SUPPORT_B),
  DECLARE_REG (28, "gb", REG_SUPPORT_B),
  DECLARE_REG (28, "rgb", REG_SUPPORT_B),
  DECLARE_REG (28, "rdb", REG_SUPPORT_B),
  DECLARE_REG (29, "tb", REG_SUPPORT_B),
  DECLARE_REG (29, "rtb", REG_SUPPORT_B),
  DECLARE_REG (30, "svbr", REG_SUPPORT_A),
  DECLARE_REG (31, "tls", REG_SUPPORT_B),

  /* The followings JAVA/BCTM's features.  */
  DECLARE_REG (23, "fp", REG_SUPPORT_ALL),
  DECLARE_REG (24, "top", REG_SUPPORT_ALL),
  DECLARE_REG (25, "bsp", REG_SUPPORT_ALL),
};

static struct csky_reg_def csky_abiv2_control_regs[] = 
{

#ifdef DECLARE_REG
#undef DECLARE_REG
#endif
  /* Bank0.  */
#define DECLARE_REG(regno, abi_name)		\
  {0, regno, "cr<"#regno", 0>", abi_name, REG_SUPPORT_ALL, NULL}
  DECLARE_REG (0, "psr"),
  DECLARE_REG (1, "vbr"),
  DECLARE_REG (2, "epsr"),
  DECLARE_REG (3, "fpsr"),
  DECLARE_REG (4, "epc"),
  DECLARE_REG (5, "fpc"),
  DECLARE_REG (6, "ss0"),
  DECLARE_REG (7, "ss1"),
  DECLARE_REG (8, "ss2"),
  DECLARE_REG (9, "ss3"),
  DECLARE_REG (10, "ss4"),
  DECLARE_REG (11, "gcr"),
  DECLARE_REG (12, "gsr"),
  DECLARE_REG (13, "cpid"),
  DECLARE_REG (14, "dcsr"),
  DECLARE_REG (15, NULL),
  DECLARE_REG (16, NULL),
  DECLARE_REG (17, "cfr"),
  DECLARE_REG (18, "ccr"),
  DECLARE_REG (19, "capr"),
  DECLARE_REG (20, "pacr"),
  DECLARE_REG (21, "prsr"),
  DECLARE_REG (22, "cir"),
  DECLARE_REG (23, "ccr2"),
  DECLARE_REG (24, NULL),
  DECLARE_REG (25, "cer2"),
  DECLARE_REG (26, NULL),
  DECLARE_REG (27, NULL),
  DECLARE_REG (28, "rvbr"),
  DECLARE_REG (29, "rmr"),
  DECLARE_REG (30, "mpid"),

#undef DECLARE_REG
#define DECLARE_REG(regno, abi_name, support)		\
  {0, regno, "cr<"#regno", 0>", abi_name, support, NULL}
  DECLARE_REG (31, "chr", REG_SUPPORT_E),
  DECLARE_REG (31, "hint", REG_SUPPORT_C),

  /* Bank1.  */
#undef DECLARE_REG
#define DECLARE_REG(regno, abi_name)		\
  {1, regno, "cr<"#regno", 1>", abi_name, REG_SUPPORT_ALL, NULL}

  DECLARE_REG (14, "usp"),
  DECLARE_REG (26, "cindex"),
  DECLARE_REG (27, "cdata0"),
  DECLARE_REG (28, "cdata1"),
  DECLARE_REG (29, "cdata2"),
  DECLARE_REG (30, "cdata3"),
  DECLARE_REG (31, "cins"),

  /* Bank2.  */
#undef DECLARE_REG
#define DECLARE_REG(regno, abi_name)		\
  {2, regno, "cr<"#regno", 2>", abi_name, REG_SUPPORT_ALL, NULL}

  DECLARE_REG (0, "fid"),
  DECLARE_REG (1, "fcr"),
  DECLARE_REG (2, "fesr"),

  /* Bank3.  */
#undef DECLARE_REG
#define DECLARE_REG(regno, abi_name)		\
  {3, regno, "cr<"#regno", 3>", abi_name, REG_SUPPORT_ALL, NULL}
  DECLARE_REG (8, "dcr"),
  DECLARE_REG (8, "sedcr"),
  DECLARE_REG (9, "pcr"),
  DECLARE_REG (9, "sepcr"),

  /* Bank15.  */
#undef DECLARE_REG
#define DECLARE_REG(regno, abi_name)		\
  {15, regno, "cr<"#regno", 15>", abi_name, REG_SUPPORT_ALL, NULL}

  DECLARE_REG (0, "mir"),
  DECLARE_REG (2, "mel0"),
  DECLARE_REG (3, "mel1"),
  DECLARE_REG (4, "meh"),
  DECLARE_REG (6, "mpr"),
  DECLARE_REG (8, "mcir"),
  DECLARE_REG (28, "mpgd0"),
  DECLARE_REG (29, "mpgd"),
  DECLARE_REG (29, "mpgd1"),
  DECLARE_REG (30, "msa0"),
  DECLARE_REG (31, "msa1"),
#undef DECLARE_REG
};

static inline const char *
get_register_name (struct csky_reg_def *preg, unsigned int size,
	       	int arch, int bank, int regno, int is_abi)
{
  static char regname[64] = {0};
  unsigned int i = 0;
  for (i = 0; i < size; i++)
    {
      if (preg[i].bank == bank
	  && preg[i].regno == regno
	  && (preg[i].supportes & SH(arch)))
        {
	  if (is_abi && preg[i].abi_name)
	    return preg[i].abi_name;
          else
	    return preg[i].name;
	}
    }

  if (bank & 0x80000000)
    return "unkown register";

  sprintf (regname, "cr<%d, %d>", regno, bank);

  return regname;
}

static inline const int
get_register_number (struct csky_reg_def *preg, unsigned int size,
	       	int arch, char *s, char **end, int *bank)
{
  unsigned int i = 0;
  int len = 0;
  for (i = 0; i < size; i++)
    {
      len = strlen (preg[i].name);
      if ((strncasecmp (preg[i].name, s, len) == 0)
	  && !(ISDIGIT(s[len]))
	  && (preg[i].supportes & SH(arch)))
        {
	  *end = s + len;
	  *bank = preg[i].bank;
	  return preg[i].regno;
        }

      if (preg[i].abi_name == NULL)
	continue;

      len = strlen (preg[i].abi_name);
      if ((strncasecmp (preg[i].abi_name, s, len) == 0)
	  && !(ISALNUM(s[len]))
	  && (preg[i].supportes & SH(arch)))
        {
	  *end = s + len;
	  *bank = preg[i].bank;
	  return preg[i].regno;
        }
    }
  return -1;
}

/* General register.  */
static const char * csky_get_general_reg_name (int arch, int regno, int is_abi)
{
  struct csky_reg_def *preg;
  unsigned int size = 0;

  if (IS_CSKY_ARCH_V1(arch))
    {
      preg = csky_abiv1_general_regs;
      size = ARRAY_SIZE(csky_abiv1_general_regs);
    }
  else
    {
      preg = csky_abiv2_general_regs;
      size = ARRAY_SIZE(csky_abiv2_general_regs);
    }

  return get_register_name (preg, size, arch,
		  GENARAL_REG_BANK, regno, is_abi);
}

static int csky_get_general_regno(int arch, char *s, char **end)
{
  struct csky_reg_def *preg;
  unsigned int size = 0;
  int bank = 0;

  if (IS_CSKY_ARCH_V1(arch))
    {
      preg = csky_abiv1_general_regs;
      size = ARRAY_SIZE(csky_abiv1_general_regs);
    }
  else
    {
      preg = csky_abiv2_general_regs;
      size = ARRAY_SIZE(csky_abiv2_general_regs);
    }

  return get_register_number (preg, size, arch, s, end, &bank);
}

/* Control register.  */
static const char * csky_get_control_reg_name (int arch, int bank, int regno, int is_abi)
{
  struct csky_reg_def *preg;
  unsigned int size = 0;

  if (IS_CSKY_ARCH_V1(arch))
    {
      preg = csky_abiv1_control_regs;
      size = ARRAY_SIZE(csky_abiv1_control_regs);
    }
  else
    {
      preg = csky_abiv2_control_regs;
      size = ARRAY_SIZE(csky_abiv2_control_regs);
    }

  return get_register_name (preg, size, arch, bank,
		  regno, is_abi);
}

static int csky_get_control_regno(int arch, char *s, char **end, int *bank)
{
  struct csky_reg_def *preg;
  unsigned int size = 0;

  if (IS_CSKY_ARCH_V1(arch))
    {
      preg = csky_abiv1_control_regs;
      size = ARRAY_SIZE(csky_abiv1_control_regs);
    }
  else
    {
      preg = csky_abiv2_control_regs;
      size = ARRAY_SIZE(csky_abiv2_control_regs);
    }


  return get_register_number (preg, size, arch, s, end, bank);
}

#endif
