@c Copyright (C) 1996-2016 Free Software Foundation, Inc.
@c This is part of the GAS manual.
@c For copying conditions, see the file as.texinfo.

@ifset GENERIC
@page
@node CSKY-Dependent
@chapter CSKY Dependent Features
@end ifset

@ifclear GENERIC
@node Machine Dependencies
@chapter CSKY Dependent Features
@end ifclear

@cindex CSKY support
@menu
* CSKY Options::              Options
* CSKY Syntax::               Syntax
* CSKY Opcodes::              Opcodes
* CSKY Mapping Symbols::      Mapping Symbols
@end menu

@node CSKY Options
@section Options
@cindex CSKY options (none)
@cindex options for CSKY (none)

@table @code
There are a few options for C-SKY assembler, the details are following:

@cindex @code{-mcpu=} command line option, CSKY
@item -mcpu=@var{processor}
This option specifies the target processor.  The assembler will issue an
error message if an attempt is made to assemble an instruction which
will not execute on the target processor.  The following processor names are
recognized:
@code{ck510},
@code{ck510e},
@code{ck520},
@code{ck610},
@code{ck610e},
@code{ck610f},
@code{ck610ef},
@code{ck801},
@code{ck801t},
@code{ck802},
@code{ck802j},
@code{ck802t},
@code{ck803},
@code{ck803h},
@code{ck803t},
@code{ck803ht},
@code{ck803f},
@code{ck803fh},
@code{ck803e},
@code{ck803ef},
@code{ck803efh},
@code{ck803eft},
@code{ck803efht},
@code{ck803eh},
@code{ck803eht},
@code{ck803et},
@code{ck803ft},
@code{ck803r1},
@code{ck803hr1},
@code{ck803tr1},
@code{ck803htr1},
@code{ck803fr1},
@code{ck803fhr1},
@code{ck803er1},
@code{ck803ehr1},
@code{ck803etr1},
@code{ck803ehtr1},
@code{ck803efr1},
@code{ck803efhr1},
@code{ck803ftr1},
@code{ck803eftr1},
@code{ck803efhtr1},
@code{ck803r2},
@code{ck803vr2},
@code{ck803hr2},
@code{ck803tr2},
@code{ck803htr2},
@code{ck803fr2},
@code{ck803fhr2},
@code{ck803er2},
@code{ck803ehr2},
@code{ck803etr2},
@code{ck803ehtr2},
@code{ck803efr2},
@code{ck803efhr2},
@code{ck803ftr2},
@code{ck803eftr2},
@code{ck803efhtr2},
@code{ck804},
@code{ck804e},
@code{ck804ef},
@code{ck804eft},
@code{ck804et},
@code{ck804f},
@code{ck804ft},
@code{ck804v},
@code{ck805},
@code{ck805e},
@code{ck805ef},
@code{ck805eft},
@code{ck805et},
@code{ck805f},
@code{ck805ft},
@code{ck807},
@code{ck807e},
@code{ck807ef},
@code{ck807f},
@code{ck810},
@code{ck810e},
@code{ck810ef},
@code{ck810eft},
@code{ck810et},
@code{ck810f},
@code{ck810ft},
@code{ck810ftv},
@code{ck810fv},
@code{ck810v},
@code{ck860},
@code{ck860f},
and
@code{ck860fv}.

Some extensions may be restricted to particular architectures; this is
documented in the list of extensions below.

@cindex @code{-march=} command line option, CSKY
@item -march=@var{architecture}
This option specifies the target architecture.  The assembler will issue
an error message if an attempt is made to assemble an instruction which
will not execute on the target architecture.  The following architecture
names are recognized:
@code{ck510},
@code{ck610},
@code{ck801},
@code{ck802},
@code{ck803},
@code{ck804},
@code{ck805},
@code{ck807},
@code{ck810},
and
@code{ck860},
If both @code{-mcpu} and
@code{-march} are specified, the assembler will use
the setting for @code{-mcpu}.

The architecture option can be extended with the same instruction set
extension options as the @code{-mcpu} option.

@cindex @code{-EB} command line option, CSKY
@cindex @code{-mbig-endian} command line option, CSKY
@item -EB
@item -mbig-endian
This option specifies that the output generated by the assembler should
be marked as being encoded for a big-endian processor.

@cindex @code{-EL} command line option, CSKY
@cindex @code{-mlittle-endian} command line option, CSKY
@item -EL
@item -mlittle-endian
This option specifies that the output generated by the assembler should
be marked as being encoded for a little-endian processor.

Note: The assembler will mark the output as a little-endian object by default.

@cindex @code{-pic} command line option, CSKY
@cindex @code{-fpic} command line option, CSKY
@item -pic
@item -fpic
This option specifies that jump instrucitons will genarate dynamic relocations.

@cindex @code{-m@{no-@}ljump} command line option, CSKY
@item -m@{no-@}ljump
This option indicates that some directives will be translated to 'jmpi' or not.

Default: disable

@cindex @code{-m@{no-@}force2bsr} command line option, CSKY
@item -m@{no-@}force2bsr
This option indicates that 'jbsr' will be translated to 'bsr' or not.

Default: disable

@cindex @code{-m@{no-@}jsri2bsr} command line option, CSKY
@item -m@{no-@}jsri2bsr
This option indicates that 'jsri' will be translated to 'bsr' or not.

Default: disable

@cindex @code{-mnolrw} command line option, CSKY
@item -mnolrw
This option indicates that 'lrw' will be translated to 'movi/movih' or not.

Default: disable

@cindex @code{-m@{no-@}literals-after-func} command line option, CSKY
@item -m@{no-@}literals-after-func
@item -m@{no-@}laf
This option indicates that enable dump literals after every function or not.

Default: disable

@cindex @code{-m@{no-@}anchor} command line option, CSKY
@item -m@{no-@}anchor
This option indicates that 'lrw' will be translated to addi rtb/rdb + offset or not.

Default: disable

@cindex @code{-m@{no-@}elrw} command line option, CSKY
@item -m@{no-@}elrw
This option indicates that 'lrw' will be translated to addi rtb/rdb + offset or not.

Default: disable

@cindex @code{-m@{no-@}literals-after-br} command line option, CSKY
@item -m@{no-@}literals-after-br
@item -m@{no-@}labr
This option indicates that the assembler dump literals after every br instruction or not.

Default: enable

@cindex @code{-m@{no-@}istack} command line option, CSKY
@item -m@{no-@}istack
This option indicates that using nie/nir/ipop/ipush intructions in the interrupt services.

Default: Enable in CK801/CK802/CK803 architecture, and others disable.

@cindex @code{-mcallgraph} command line option, CSKY
@item -mcallgraph
This option indicates that the assembler genarates callgraph file which records
functions-call-stack-depths.

Default: disable

@cindex @code{-m@{no-@}callgraph} command line option, CSKY
@item -m@{no-@}callgraph
This option indicates that reserve function call related relocs or not.

Default: enable

@cindex @code{-m@{no-@}callgraph-reloc} command line option, CSKY
@item -m@{no-@}callgraph-reloc
This option indicates that emit callgraph reloc information or not.

Default: diable

@cindex @code{-mmp} command line option, CSKY
@item -mmp
This option indicates that support multiple processor instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mcp} command line option, CSKY
@item -mcp
This option indicates that support corprocessor instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mdsp} command line option, CSKY
@item -mdsp
This option indicates that support DSP instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mcache} command line option, CSKY
@item -mcache
This option indicates that support cache prefetch instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-msecurity} command line option, CSKY
@item -msecurity
This option indicates that support security instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mhard-float} command line option, CSKY
@item -mhard-float
This option indicates that support hard-flaot instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mtrust} command line option, CSKY
@item -mtrust
This option indicates that support trust instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-medsp} command line option, CSKY
@item -medsp
This option indicates that support enhance-DSP instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@cindex @code{-mvdsp} command line option, CSKY
@item -mvdsp
This option indicates that support vector-DSP instructions set.
It will be contained by @code{-mcpu=} option normally.

Default: not support.

@end table


@node CSKY Syntax
@section Syntax
@menu
* CSKY-Chars::                Special Characters
* CSKY-Regs::                 Register Names
@end menu

@node CSKY-Chars
@subsection Special Characters

@cindex line comment character, CSKY
@cindex CSKY line comment character
The presence of a @samp{//} anywhere on a line indicates the start of
a comment that extends to the end of that line.

If a @samp{#} appears as the first character of a line then the whole
line is treated as a comment, but in this case the line could also be
a logical line number directive (@pxref{Comments}) or a preprocessor
control command (@pxref{Preprocessing}).

@cindex line separator, CSKY
@cindex statement separator, CSKY
@cindex CSKY line separator
The @samp{;} character can be used instead of a newline to separate
statements.

@node CSKY-Regs
@subsection Register Names

@cindex CSKY register names
@cindex register names, CSKY
Normally, you can use 'rn'/'Rn'(n are [0,31]) indicates general registers,
eg. 'r0', 'R15', ...
In addition, you can use alias names, such as 'sp', 'lr' and so on.

@node CSKY Opcodes
@section Opcodes

@cindex CSKY opcodes
@cindex opcodes CSKY
@code{@value{AS}} implements all the standard CSKY opcodes.  It also
implements several pseudo opcodes.

@table @code

@cindex @code{NOP} pseudo op, CSKY
@item NOP
@smallexample
  nop
@end smallexample

This pseudo op will always evaluate to a legal CSKY instruction that does
nothing.  It will evaluate to "MOV r0, r0".

@cindex @code{clrc} pseudo op, CSKY
@item setc
@smallexample
  setc
@end smallexample

This pseudo op will set the condition code bit(C) in the PSR(Process Status Register).
It will evaluate to "CMPHS r0, r0".

@cindex @code{clrc} pseudo op, CSKY
@item clrc
@smallexample
  clrc
@end smallexample

This pseudo op will clear the condition code bit(C) in the PSR(Process Status Register).
It will evaluate to "CMPNE r0, r0".

@cindex @code{cmplei} pseudo op, CSKY
@item cmplei
@smallexample
  cmplei rd, n
@end smallexample

This pseudo op will compare rd with imm n as signed value. If rd <= n, it will set the
condition code bit(C) int the PSR.
It will evaluate to "CMPLTI rd, n+1".

@cindex @code{cmpls} pseudo op, CSKY
@item cmpls
@smallexample
  cmpls rd, rs
@end smallexample

This pseudo op will compare rd with rs as unsigned value. If rd <= rs, it will set the
condition code bit(C) int the PSR.
It will evaluate to "CMPHS rs, rd".

@cindex @code{cmpgt} pseudo op, CSKY
@item cmpgt
@smallexample
  cmpgt rd, rs
@end smallexample

This pseudo op will compare rd with rs as signed value. If rd >= n, it will set the
condition code bit(C) int the PSR.
Currently it will evaluate to "CMPLT rs, rd".

@cindex @code{jbsr} pseudo op, CSKY
@item jbsr
@smallexample
  jbsr label
@end smallexample

This pseudo op will call the subroutine identified by label. Use the
relative branch to subroutine instruction if the subroutine is within
range, otherswaise use an absolute jump to subroutine.

It will evaluate to "bsr label" or "jsri label".

@cindex @code{jbr} pseudo op, CSKY
@item jbr
@smallexample
  jbr label
@end smallexample

Continue execution at the instruction identified by label. Use the
relative branch instruction if the label is within range, otherswaise
use an absolute jump to the label.

It will evaluate to:
@smallexample
  br label
@end smallexample
or
@smallexample
  jmpi label
@end smallexample

@cindex @code{jbf} pseudo op, CSKY
@item jbf
@smallexample
  jbf label
@end smallexample

Continue execution at the instruction identified by label only if the
condition code bit is false. Use the relative branch instruction if
the label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  bf label
@end smallexample
or
@smallexample
  bt 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jbt} pseudo op, CSKY
@item jbt
@smallexample
  jbt label
@end smallexample

Continue execution at the instruction identified by label only if the
condition code bit is true. Use the relative branch instruction if
the label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  bt label
@end smallexample
or
@smallexample
  bf 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{rts} pseudo op, CSKY
@item rts
@smallexample
  rts
@end smallexample

Return from subroutine. It will evaluate to "jmp r15".

@cindex @code{neg} pseudo op, CSKY
@item neg
@smallexample
  neg rd
@end smallexample

Negates the value in rd. It will evaluate to:
In C-SKY ABI version 1:
@smallexample
  rsubi rd, 0
@end smallexample
In C-SKY ABI version 2:
@smallexample
  not rd, rd
  addi rd, 1
@end smallexample

@cindex @code{rotlc} pseudo op, CSKY
@item rotlc
@smallexample
  rotlc rd, 1
@end smallexample

Rotates the value in rd left by one bit. The carry bit is rotated into
least significant bit while the most significant bit that was rotated
out is saved in the carry bit. It will evaluate to "ADDC rd, rd".

@cindex @code{rotri} pseudo op, CSKY
@item rotri
@smallexample
  rotri rd, imm
@end smallexample

Rotates the value in rd left by the number of bits specified in imm.
It will evaluate to "ROTLI rd, 32-imm".

@cindex @code{tstlt} pseudo op, CSKY
@item tstlt
@smallexample
  tstlt rd
@end smallexample

Test for a negative value in the specified register.
It will evaluate to "BTSTI rd, 31".

@cindex @code{tstle} pseudo op, CSKY
@item tstle
@smallexample
  tstle rd
@end smallexample

Test for a negative or zero value in the specified register.
It will evaluate to "CMPLTI rd, 1".

@cindex @code{tstne} pseudo op, CSKY
@item tstne
@smallexample
  tstne rd
@end smallexample

Test for a non-zero value in the specified register.
It will evaluate to "CMPNEI rd, 0".

@cindex @code{bgeni} pseudo op, CSKY
@item bgeni
@smallexample
  bgeni rz, imm
@end smallexample

Generate a value which the @code{imm} bit is 1 and others 0.
It will evaluate to "MOVI rz, 2^imm".

@cindex @code{ldq} pseudo op, CSKY
@item ldq
@smallexample
  ldq r4-r7, (rx)
@end smallexample

Load @code{r4-r7} from memory address specified @code{rx}.
It will evaluate to @code{ldm r4-r7, (rx)}.

@cindex @code{movf} pseudo op, CSKY
@item movf
@smallexample
  movf rz, rx
@end smallexample

Execution mov if bit C == 0. It will evaluate to @code{incf rz, rx, 0}.

@cindex @code{movt} pseudo op, CSKY
@item movt
@smallexample
  movt rz, rx
@end smallexample

Execution mov if bit C == 1. It will evaluate to @code{inct rz, rx, 0}.

@cindex @code{not} pseudo op, CSKY
@item not
@smallexample
  not rz, rx
@end smallexample

Store the value of reversing rx to rz. It will evaluate to @code{nor rz, rx, rx}.

@cindex @code{rsub} pseudo op, CSKY
@item rsub
@smallexample
  rsub rz, rx, ry
@end smallexample

Execution ry sub rx. It will evaluate to @code{sub rz, ry, rx}.

@cindex @code{sextb} pseudo op, CSKY
@item sextb
@smallexample
  sextb rz, rx
@end smallexample

rz[7:0] = rx[7:0], rz[31-8] = rx[7].
It will evaluate to @code{sext rz, rx, 7, 0}.

@cindex @code{sexth} pseudo op, CSKY
@item sexth
@smallexample
  sexth rz, rx
@end smallexample

rz[15:0] = rx[15:0], rz[31-16] = rx[15].
It will evaluate to @code{sext rz, rx, 15, 0}.

@cindex @code{zextb} pseudo op, CSKY
@item zextb
@smallexample
  zextb rz, rx
@end smallexample

rz[7:0] = rx[7:0]. It will evaluate to @code{zext rz, rx, 7, 0}.

@cindex @code{zexth} pseudo op, CSKY
@item zexth
@smallexample
  zexth rz, rx
@end smallexample

rz[15:0] = rx[15:0]. It will evaluate to @code{zext rz, rx, 15, 0}.

@cindex @code{jbez} pseudo op, CSKY
@item jbez
@smallexample
  jbez rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} equal 0. Use the relative branch instruction if the label
is within range, otherswaise use a conditional branch around jump
to the label.

It will evaluate to:
@smallexample
  bez rx, label
@end smallexample
or
@smallexample
  bnez rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jbnez} pseudo op, CSKY
@item jbnez
@smallexample
  jbnez rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} not equal 0. Use the relative branch instruction if the
label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  bnez rx, label
@end smallexample
or
@smallexample
  bez rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jbhz} pseudo op, CSKY
@item jbhz
@smallexample
  jbhz rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} > 0. Use the relative branch instruction if the
label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  bhz rx, label
@end smallexample
or
@smallexample
  blsz rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jblsz} pseudo op, CSKY
@item jblsz
@smallexample
  jblsz rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} <= 0. Use the relative branch instruction if the
label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  blsz rx, label
@end smallexample
or
@smallexample
  bhz rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jblz} pseudo op, CSKY
@item jblz
@smallexample
  jblz rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} < 0. Use the relative branch instruction if the
label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  blz rx, label
@end smallexample
or
@smallexample
  bhsz rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@cindex @code{jbhsz} pseudo op, CSKY
@item jbhsz
@smallexample
  jbhsz rx, label
@end smallexample

Continue execution at the instruction identified by label only if
@code{rx} >= 0. Use the relative branch instruction if the
label is within range, otherswaise use a conditional branch around
jump to the label.

It will evaluate to:
@smallexample
  bhsz rx, label
@end smallexample
or
@smallexample
  blz rx, 1f
  br/jmpi label
  1:
    ...
@end smallexample

@end table

@node CSKY Mapping Symbols
@section Mapping Symbols

The CSKY ELF specification requires that special symbols be inserted
into object files to mark certain features:

@table @code

@cindex @code{$t}
@item $t
At the start of a region of code.

@cindex @code{$d}
@item $d
At the start of a region of data.

@end table

The assembler will automatically insert these symbols for you - there
is no need to code them yourself.

